324 move to ghcr
defencedigital/spa-server pull request #3
Opened 2021-03-30 10:24 UTC by RainThief

2021-04-01 06:42 UTC, lukaszraczylo requested changes

2021-04-01 06:42 UTC, lukaszraczylo commented on .github/workflows/push.yml
> +  DOCKER_PASS: ${{ secrets.ADMIN_GITHUB_TOKEN }}
I think we should unify it with `GHCR_TOKEN` as per other repositories so if the #378 is closed we won't need to make the change

2021-04-06 08:59 UTC, RainThief commented on .github/workflows/push.yml
> +  DOCKER_PASS: ${{ secrets.ADMIN_GITHUB_TOKEN }}
done

2021-04-06 09:31 UTC, lukaszraczylo approved these changes

2021-04-06 14:36 UTC, merged