[447] move to nginx
defencedigital/spa-server pull request #4
Opened 2021-05-13 18:49 UTC by lukaszraczylo

As per specification from https://trello.com/c/WjvMu95J/447-recreate-spa-server

2021-05-13 19:26 UTC, RainThief commented on static/vhost.conf
> +}
Stub to allow me time to review  before merge

2021-05-13 20:15 UTC, lukaszraczylo commented on static/vhost.conf
> +}
As per our chat - to verify it works:
```
docker pull docker.pkg.github.com/defencedigital/r2d2-spa/r2d2-spa
docker create $outputFromAbove
docker copy $outputFromAbove:/var/www/html ./spa
```

2021-05-13 21:16 UTC, RainThief commented on static/vhost.conf
> +  gzip_types text/plain application/xml application/json application/javascript application/x-javascript text/javascript text/xml text/css;
bo be on the safe side, just incase we use in future
application/json application/vnd.ms-fontobject image/svg+xml application/x-font-ttf font/opentype font/woff

2021-05-13 21:16 UTC, RainThief commented on static/vhost.conf
> +  # I am not expiring html and json purposedly - in the event of website rebuild
## NIT

makes perfect sense

2021-05-13 21:16 UTC, RainThief commented on static/vhost.conf
> +    expires max;
I have checked and css, js is hash mapped so we can use this long expires but for the others maybe dial back a little bit

```
location ~* \.(gif|ico|png|jpg|jpeg|woff|woff2|ttf|otf|svg)$ {
   expires 90d;
}
```

2021-05-13 21:16 UTC, RainThief commented on static/vhost.conf
> +  # to non-existent chunks - user will not be able to access the website
to ensure correct functioning of expires headers i suggest to disable etag
```
etag off;
```

2021-05-13 21:16 UTC, RainThief commented on static/vhost.conf
> +}
are you going to raise a pr for the SPA to use this new container as it base?  I could then test from there which would be most useful.

To be true to the process, it was not explicit in the acceptance criteria but assumed when i write ticket, so please raise a new ticket otherwise, your choice

2021-05-13 21:16 UTC, RainThief commented on README.md
> +As of May 2020 we have switched to nginx mainline.
no not mainline, I know docs say use mainline over stable but we should pin as per dds rules (yet to be documented)

2021-05-13 21:16 UTC, RainThief commented on static/vhost.conf
> +  # ssl_stapling_verify on;
i see no reason to use stapling, lets remove comments

2021-05-13 21:20 UTC, lukaszraczylo commented on static/vhost.conf
> +}
I'll do it as a part of the ticket after this one is merged

2021-05-13 21:29 UTC, lukaszraczylo commented on .github/workflows/push.yml
> +  VERSION: 0.0.2
That's exactly why I've hardcoded the version for now. I can add the content of https://github.com/defencedigital/spa-server/blob/main/scripts/semver.sh to automatically bump the version if that's what you're looking for

2021-05-14 06:08 UTC, RainThief commented on static/vhost.conf
> +  ssl_certificate_key /etc/ssl/private/self-signed.key;
Can we put the cert location in an include file as if we needed to use real carts in future on deployment with k8s then we only need a config map for two directives

2021-05-14 06:22 UTC, lukaszraczylo commented on Dockerfile
> +ADD certs/self-signed.crt /etc/ssl/certs/self-signed.crt
We have discussed it. I said that we can terminate SSL on the ELB, you replied with "zero trust" and SSL baked into every container hence why you have certificates baked in.

Acceptance criteria mention "TLS certificate configuration" as well.
I've added the commands included for certificate generation as a hint - I can add them to the Dockerfile and generate a new certificate on every build if that's okay :)

2021-05-14 06:32 UTC, lukaszraczylo commented on static/vhost.conf
> +  ssl_certificate_key /etc/ssl/private/self-signed.key;
When we use it in the kubernetes those can be easily replaced by the mount via config maps as you mentioned. I've changed that to `/etc/ssl/private-custom` to not overwrite anything what may be in there

2021-05-14 06:32 UTC, lukaszraczylo commented on static/vhost.conf
> +  # ssl_stapling_verify on;
That's done :)

2021-05-14 06:32 UTC, lukaszraczylo commented on README.md
> +As of May 2020 we have switched to nginx mainline.
That's done :)

2021-05-14 06:32 UTC, lukaszraczylo commented on static/vhost.conf
> +  # to non-existent chunks - user will not be able to access the website
That's done :)

2021-05-14 06:32 UTC, lukaszraczylo commented on static/vhost.conf
> +    expires max;
That's done :)

2021-05-14 06:33 UTC, lukaszraczylo commented on Dockerfile
> +FROM nginx:mainline
That's done :)

2021-05-14 06:49 UTC, lukaszraczylo commented on .github/workflows/push.yml
> +  VERSION: 0.0.2
semver.sh added - seems to be working just fine

2021-05-14 06:51 UTC, lukaszraczylo commented on static/vhost.conf
> +  gzip_types text/plain application/xml application/json application/javascript application/x-javascript text/javascript text/xml text/css;
Done ✅

2021-05-14 06:59 UTC, lukaszraczylo commented
@RainThief I think we will need to remove requirements for Check and Test tests that do not exist after the changes, otherwise builds will get stuck in pending

2021-05-14 08:00 UTC, RainThief commented on static/vhost.conf
> +  ssl_certificate_key /etc/ssl/private/self-signed.key;
so what I am thinking, is if we have a separate config `snippet` that can be used as a config map for different envs.  so for an example, my temp stack showing head of each container, i can create my own snippet to mount into the container so i can use lets encrypt and put basic auth onto protecting site from public views.  Otherwise I would need to override the whole config file and then need to keep my version in line with head of this project.

2021-05-14 08:01 UTC, RainThief commented on .github/workflows/push.yml
> +  VERSION: 0.0.2
is this fully tested, the semver script just reads a git tag and bumps but does not push the tag back.  therfore next run would give exactly same version

2021-05-14 08:04 UTC, RainThief commented on Dockerfile
> +ADD certs/self-signed.crt /etc/ssl/certs/self-signed.crt
The ticket hasnt been updated, we have had so many tickets to juggle.  So we all know that we dropped the zero trust for now approach but will do it in future.  Please lets get into habit of kick offs as this would have been discussed.
Unsure of how balancers work, if they passthrough the connection does the upstream need to be HTTP/2 or would the balancer handle this?
But certs in now and are needed one day so keep it as it

2021-05-14 08:11 UTC, RainThief commented on README.md
> +As of May 2020 we have switched to nginx 1.20.
you just know when we bump to 1.21 this will be left out of sync :)

```suggestion
As of May 2020 we have switched to nginx
```

2021-05-14 08:46 UTC, casparrolfe commented on Dockerfile
> +ADD certs/self-signed.crt /etc/ssl/certs/self-signed.crt
I think certs will be needed if we use this https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html

There are a couple of approaches we can take that probably need a really quick chat to figure out which one we want to do.

I guess there are two approaches we could take locally. We can either just listen on HTTP and forget about HTTPS (we don't bother setting up TLS for Postgres, for example) or use self signed certs. Maybe there's not a ton of value to the latter since we'll have to disable checks when it comes to service to service communication?

2021-05-14 09:16 UTC, lukaszraczylo commented on Dockerfile
> +ADD certs/self-signed.crt /etc/ssl/certs/self-signed.crt
Resolved with 417d1d8

AWS ALBs support http/2 - https://aws.amazon.com/blogs/aws/new-application-load-balancer-support-for-end-to-end-http-2-and-grpc/
I think we can have a fully qualified SSL certificate on the ALB and the communication between ALB and the nginx will be encrypted with the certificate we provide which will provide additional security as users passwords will be provided during the login

2021-05-14 09:18 UTC, lukaszraczylo commented on .github/workflows/push.yml
> +  VERSION: 0.0.2
It is exactly how it was before I believe, I'm simply executing the script which was there before work on the ticket started. It generates the version - which is not applied unless the merge to master/main happens

2021-05-14 10:54 UTC, RainThief commented on .github/workflows/push.yml
> +  VERSION: 0.0.2
It never gets applied.  the docker image will get tagged with semver but no tag happens within git.  so on next run to master it will create the same docker tag and overwrite as the git tag never changed.

You will need something like

```
git tag "v$SEMVER"
git push --tags
```

2021-05-14 10:59 UTC, RainThief commented
> @RainThief I think we will need to remove requirements for Check and Test tests that do not exist after the changes, otherwise builds will get stuck in pending



> @RainThief I think we will need to remove requirements for Check and Test tests that do not exist after the changes, otherwise builds will get stuck in pending

can you ask @Digitiain as I do not have admin

2021-05-14 15:59 UTC, RainThief commented on static/vhost.conf
> +  }
I tested this container and it does not redirect all no found routes to index

![image](https://user-images.githubusercontent.com/20727286/118297043-8e197980-b4d5-11eb-8ca4-141043a84fa1.png)

Suggest trying a try_files rule

```
location / {
       try_files $uri $uri/ /index.html;
}
```

2021-05-14 15:59 UTC, RainThief commented on static/vhost.conf
> +  index index.html index.htm;
can confirm reacy generates `index.html`

2021-05-14 19:16 UTC, lukaszraczylo commented on .github/workflows/push.yml
> +  VERSION: 0.0.2
Added in 9c919a0

2021-05-14 19:17 UTC, lukaszraczylo commented on README.md
> +As of May 2020 we have switched to nginx 1.20.
Removed in 91d4b48

2021-05-14 19:18 UTC, lukaszraczylo commented on static/vhost.conf
> +  }
Added in 2257975

2021-05-14 19:19 UTC, lukaszraczylo commented on static/vhost.conf
> +  index index.html index.htm;
I believe you meant react, yes - in this case it's valid although I guess you mentioned it because you'd like index.htm removed - therefore it's removed in fe9a9f6

2021-05-14 19:39 UTC, RainThief commented on static/vhost.conf
> +  index index.html index.htm;
Lol, i thought you added both as you didn't know. No issue leaving htm in but it's not needed

2021-05-14 19:39 UTC, RainThief commented on static/vhost.conf
> +  }
Does it work, did you test it?

2021-05-14 20:12 UTC, lukaszraczylo commented on static/vhost.conf
> +  }
Seems to be working as far as I could get without logging in

2021-05-17 09:03 UTC, RainThief commented on .github/workflows/push.yml
> +          fi
@lukaszraczylo please keep an eye on this merging to main branch to check it functions as expected

2021-05-17 09:04 UTC, RainThief commented
@lukaszraczylo please see comment on ticket about non ssl, concerned we will deploy a broken dev stack to mac users
https://trello.com/c/WjvMu95J/447-recreate-spa-server

2021-05-17 09:10 UTC, RainThief requested changes

2021-05-17 09:10 UTC, RainThief commented on static/vhost.conf
> +  }
I cannot get this to work, clearly an error with my try files example.  How did it work for you
```
127.0.0.1 - - [17/May/2021:09:08:16 +0000] "GET / HTTP/2.0" 500 579 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "-"
2021/05/17 09:09:03 [error] 30#30: *5 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 127.0.0.1, server: _, request: "GET /index.html HTTP/2.0", host: "localhost"
```

2021-05-17 09:49 UTC, lukaszraczylo commented on static/vhost.conf
> +  }
Could you please provide me with a full bug reproduction path as two scenarios I've checked work just fine

1. SSL main page -> made up URL ( `/something/something` )
2. non-ssl `/something/better`-> SSL `/something/better`

![Screenshot 2021-05-17 at 10 48 32](https://user-images.githubusercontent.com/2182556/118469389-8fc58600-b6fd-11eb-8686-174bd092dfd7.png)

2021-05-17 10:21 UTC, RainThief commented on static/vhost.conf
> +  }
bug reproduction path = `https://localhost/` or `https://localhost/<anything>`

2021-05-17 10:21 UTC, RainThief commented on static/vhost.conf
> +  }
i am pulling ghcr.io/defencedigital/spa-server:447-move-to-nginx

2021-05-17 13:54 UTC, lukaszraczylo commented on static/vhost.conf
> +  }
Resolved in ae19a1b

2021-05-17 13:54 UTC, lukaszraczylo commented
As an addition and per ticket comments I have added additional conditional redirection which can be used during the development process.

2021-05-17 15:59 UTC, RainThief commented on static/vhost.conf
> +  }
seems to be persisting problem
![image](https://user-images.githubusercontent.com/20727286/118519731-4a22b080-b731-11eb-8f59-429eba67e317.png)

2021-05-18 06:13 UTC, lukaszraczylo commented on static/vhost.conf
> +  }
The last attempt to fix in f13b47c, please check - if it still won't work - we will need that screen sharing session

2021-05-18 08:33 UTC, RainThief commented on Dockerfile
> +# COPY spa/. /var/www/html
how are the files getting in this image?

2021-05-18 08:33 UTC, RainThief commented on static/nginx.conf
> +    #tcp_nopush     on;
delete?

2021-05-18 08:33 UTC, RainThief commented on static/vhost.conf
> +    break;
It still redirects (I built spa using new image)

![image](https://user-images.githubusercontent.com/20727286/118618422-84389480-b7bb-11eb-8718-07e36189ff4c.png)

2021-05-18 08:33 UTC, RainThief commented on static/vhost.conf
> +  }
fixed

2021-05-18 08:59 UTC, lukaszraczylo commented on Dockerfile
> +# COPY spa/. /var/www/html
It is the base image, just as the previous one - we add the files in the https://github.com/defencedigital/r2d2-spa builds. 
The line you have mentioned is the one I'm using for debugging and simulate actual files being placed in the application as per below ( extracting files from existing spa application image ):

```
docker pull docker.pkg.github.com/defencedigital/r2d2-spa/r2d2-spa
docker create $outputFromAbove
docker cp $outputFromAbove:/var/www/html ./spa
```

2021-05-18 09:00 UTC, lukaszraczylo commented on static/vhost.conf
> +    break;
```
docker run -e DISABLE_SSL_REDIRECT=true -p 80:80 -p 443:443 -it spa2
```
I think the capitalisation may matter in this case :)

2021-05-18 09:32 UTC, RainThief commented on static/vhost.conf
> +    break;
works, thanks

2021-05-18 09:33 UTC, RainThief commented on Dockerfile
> +# COPY spa/. /var/www/html
shame again, i know this as i was building it with the spa files

2021-05-18 09:33 UTC, RainThief commented on Dockerfile
> +# COPY spa/. /var/www/html
however, delete this line please

2021-05-18 09:49 UTC, lukaszraczylo commented on Dockerfile
> +# COPY spa/. /var/www/html
Not sure where I added the comment but I've deleted it right after you mentioned it in 0f8eacf :)

2021-05-18 14:27 UTC, RainThief approved these changes

2021-05-18 14:51 UTC, merged